# Generated by Django 2.0.2 on 2018-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=256)),
                ('movie_rating', models.IntegerField(blank=True, choices=[(1, 'Worse'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('watched', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
