# Generated by Django 2.0.2 on 2018-02-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
    ]
