# Generated by Django 2.0.2 on 2018-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_watched_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='l',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
