# Generated by Django 2.0.2 on 2018-02-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='l',
        ),
    ]
